<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>

    <title>Medical Report</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
      }

      .report-container {
        background: url(./assets/logo.jpg) no-repeat;
        background-position: center;
        background-size: 200px;
        
        width: 80%;
        margin: 20px auto;
        /* background: white; */
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      }

      header {
        text-align: center;
        border-bottom: 1px solid #ddd;
        margin-bottom: 20px;
      }

      header h1 {
        margin: 0;
      }

      section {
        margin-bottom: 20px;
      }

      section h2 {
        border-bottom: 1px solid #ddd;
        padding-bottom: 5px;
        margin-bottom: 10px;
      }

      .buttons {
        text-align: center;
        margin-top: 20px;
      }

      button {
        padding: 10px 20px;
        margin: 5px;
        border: none;
        background-color: #007bff;
        color: white;
        cursor: pointer;
      }

      button:hover {
        background-color: #0056b3;
      }
    </style>
  </head>
  <body>
    <div class="report-container">
      <header>
        <h1>MHS Report</h1>
        <p>Patient Name: John Doe</p>
        <p>Date: 2024-06-13</p>
      </header>
      <section class="patient-info">
        <h2>Results</h2>
        <p><strong>Score:</strong> 30</p>
        <p><strong>Status:</strong> 30</p>
        <p><strong>Stage:</strong> 30</p>
      </section>
      <section class="medical-details">
        <h2>Suggestions</h2>
        <p>
          <strong>Exercises:</strong>
          <div>
            <li style="padding: 2px;">Engaging in activities like walking, yoga and Dancing</li>
            <li style="padding: 2px;">Practice deep breathing</li>
            <li style="padding: 2px;">Staying hydrated</li>
            <li style="padding: 2px;">Listen positive music.</li>
          </div>


          <div style="padding: 10px 0px;">
            <strong style="padding: 10px 2px;">Exercises:</strong>
            <div>
                <li style="padding: 2px;">Consult to any doctor without hegitation</li>
                <li style="padding: 2px;">Do the following tasks that are mentioned below</li>
            </div>
          </div>

          <div style="padding: 10px 0px;">
            <strong style="padding: 10px 2px;">Resources:</strong>
            <div>
                <li style="padding: 2px;"><a class="text-blue-500" href="">Inhale and Exhale Games</a></li>
                <li style="padding: 2px;"><a class="text-blue-500" href="">Attend Meditation session</a></li>
            </div>
          </div>
        </p>
        <p class="text-orange-400">
          <strong>*Notes:</strong> This report is automatically generated by system.*
        </p>
      </section>
      <!-- <section class="doctor-info">
        <h2>Doctor Information</h2>
        <p><strong>Name:</strong> Dr. Jane Smith</p>
        <p><strong>Specialty:</strong> Cardiologist</p>
        <p><strong>Contact:</strong> (987) 654-3210</p>
      </section> -->
      <div class="buttons text-sm">
        <button class="px-3 py-2 rounded bg-blue-600 text-white" onclick="window.print()">Print Report</button>
        <button class="px-3 py-2 rounded bg-blue-600 text-white"  onclick="downloadPDF()">Download PDF</button>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.min.js"></script>
    <script>
      function downloadPDF() {
        const element = document.querySelector(".report-container");
        html2pdf().from(element).save("medical_report.pdf");
      }
    </script>
  </body>
</html>
